"""empty message

Revision ID: 9e0cafc8a667
Revises: initial
Create Date: 2025-07-13 18:15:18.317304

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "9e0cafc8a667"
down_revision: Union[str, Sequence[str], None] = "initial"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "indexer_utils_filterrule",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "item_type", sa.Enum("mv", "tv", name="type_choices"), nullable=False
        ),
        sa.Column("attribute", sa.String(length=64), nullable=False),
        sa.Column("operator", sa.String(length=16), nullable=False),
        sa.Column("value", sa.String(length=255), nullable=False),
        sa.Column("enabled", sa.Boolean(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("indexer_utils_filterrule")
    # ### end Alembic commands ###
