"""empty message

Revision ID: f3feb6c5579f
Revises: 9e0cafc8a667
Create Date: 2025-07-13 19:54:04.849724

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "f3feb6c5579f"
down_revision: Union[str, Sequence[str], None] = "9e0cafc8a667"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "indexer_utils_ignoreitem",
        "type",
        new_column_name="item_type",
        type_=sa.Enum("mv", "tv", name="type_choices"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    op.alter_column(
        "indexer_utils_ignoreitem",
        "item_type",
        new_column_name="type",
        type_=sa.Enum("mv", "tv", name="type_choices"),
    )
    # ### end Alembic commands ###
