"""empty message

Revision ID: initial
Revises:
Create Date: 2025-07-13 18:06:52.643836

"""

from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import mysql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "initial"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("django_session", if_exists=True)
    op.drop_table("django_admin_log", if_exists=True)
    op.drop_table("auth_user_user_permissions", if_exists=True)
    op.drop_table("django_migrations", if_exists=True)
    op.drop_table("auth_group_permissions", if_exists=True)
    op.drop_table("auth_user_groups", if_exists=True)
    op.drop_table("auth_permission", if_exists=True)
    op.drop_table("django_content_type", if_exists=True)
    op.drop_table("auth_user", if_exists=True)
    op.drop_table("auth_group", if_exists=True)
    op.alter_column(
        "indexer_utils_ignoreitem",
        "id",
        existing_type=mysql.BIGINT(),
        type_=sa.Integer(),
        existing_nullable=False,
        autoincrement=True,
    )
    op.alter_column(
        "indexer_utils_ignoreitem",
        "type",
        existing_type=mysql.VARCHAR(length=2),
        type_=sa.Enum("mv", "tv", name="type_choices"),
        existing_nullable=False,
    )
    op.alter_column(
        "indexer_utils_ignoreitem",
        "ignore",
        existing_type=mysql.TINYINT(display_width=1),
        nullable=True,
    )
    op.alter_column(
        "indexer_utils_ignoreitem",
        "added",
        existing_type=mysql.TINYINT(display_width=1),
        nullable=True,
    )
    op.alter_column(
        "indexer_utils_ignoreitem",
        "title",
        existing_type=mysql.VARCHAR(length=255),
        nullable=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "indexer_utils_ignoreitem",
        "title",
        existing_type=mysql.VARCHAR(length=255),
        nullable=False,
    )
    op.alter_column(
        "indexer_utils_ignoreitem",
        "added",
        existing_type=mysql.TINYINT(display_width=1),
        nullable=False,
    )
    op.alter_column(
        "indexer_utils_ignoreitem",
        "ignore",
        existing_type=mysql.TINYINT(display_width=1),
        nullable=False,
    )
    op.alter_column(
        "indexer_utils_ignoreitem",
        "type",
        existing_type=sa.Enum("mv", "tv", name="type_choices"),
        type_=mysql.VARCHAR(length=2),
        existing_nullable=False,
    )
    op.alter_column(
        "indexer_utils_ignoreitem",
        "id",
        existing_type=sa.Integer(),
        type_=mysql.BIGINT(),
        existing_nullable=False,
        autoincrement=True,
    )
    op.create_table(
        "auth_permission",
        sa.Column("id", mysql.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("name", mysql.VARCHAR(length=255), nullable=False),
        sa.Column(
            "content_type_id", mysql.INTEGER(), autoincrement=False, nullable=False
        ),
        sa.Column("codename", mysql.VARCHAR(length=100), nullable=False),
        sa.ForeignKeyConstraint(
            ["content_type_id"],
            ["django_content_type.id"],
            name="auth_permission_content_type_id_2f476e4b_fk_django_co",
        ),
        sa.PrimaryKeyConstraint("id"),
        mysql_default_charset="latin1",
        mysql_engine="InnoDB",
    )
    op.create_index(
        op.f("auth_permission_content_type_id_codename_01ab375a_uniq"),
        "auth_permission",
        ["content_type_id", "codename"],
        unique=True,
    )
    op.create_table(
        "auth_user_groups",
        sa.Column("id", mysql.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("user_id", mysql.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("group_id", mysql.INTEGER(), autoincrement=False, nullable=False),
        sa.ForeignKeyConstraint(
            ["group_id"],
            ["auth_group.id"],
            name=op.f("auth_user_groups_group_id_97559544_fk_auth_group_id"),
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["auth_user.id"],
            name=op.f("auth_user_groups_user_id_6a12ed8b_fk_auth_user_id"),
        ),
        sa.PrimaryKeyConstraint("id"),
        mysql_default_charset="latin1",
        mysql_engine="InnoDB",
    )
    op.create_index(
        op.f("auth_user_groups_user_id_group_id_94350c0c_uniq"),
        "auth_user_groups",
        ["user_id", "group_id"],
        unique=True,
    )
    op.create_table(
        "auth_group_permissions",
        sa.Column("id", mysql.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("group_id", mysql.INTEGER(), autoincrement=False, nullable=False),
        sa.Column(
            "permission_id", mysql.INTEGER(), autoincrement=False, nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["group_id"],
            ["auth_group.id"],
            name=op.f("auth_group_permissions_group_id_b120cbf9_fk_auth_group_id"),
        ),
        sa.ForeignKeyConstraint(
            ["permission_id"],
            ["auth_permission.id"],
            name=op.f("auth_group_permissio_permission_id_84c5c92e_fk_auth_perm"),
        ),
        sa.PrimaryKeyConstraint("id"),
        mysql_default_charset="latin1",
        mysql_engine="InnoDB",
    )
    op.create_index(
        op.f("auth_group_permissions_group_id_permission_id_0cd325b0_uniq"),
        "auth_group_permissions",
        ["group_id", "permission_id"],
        unique=True,
    )
    op.create_table(
        "django_migrations",
        sa.Column("id", mysql.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("app", mysql.VARCHAR(length=255), nullable=False),
        sa.Column("name", mysql.VARCHAR(length=255), nullable=False),
        sa.Column("applied", mysql.DATETIME(fsp=6), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        mysql_default_charset="latin1",
        mysql_engine="InnoDB",
    )
    op.create_table(
        "auth_user_user_permissions",
        sa.Column("id", mysql.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("user_id", mysql.INTEGER(), autoincrement=False, nullable=False),
        sa.Column(
            "permission_id", mysql.INTEGER(), autoincrement=False, nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["permission_id"],
            ["auth_permission.id"],
            name=op.f("auth_user_user_permi_permission_id_1fbb5f2c_fk_auth_perm"),
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["auth_user.id"],
            name=op.f("auth_user_user_permissions_user_id_a95ead1b_fk_auth_user_id"),
        ),
        sa.PrimaryKeyConstraint("id"),
        mysql_default_charset="latin1",
        mysql_engine="InnoDB",
    )
    op.create_index(
        op.f("auth_user_user_permissions_user_id_permission_id_14a6b632_uniq"),
        "auth_user_user_permissions",
        ["user_id", "permission_id"],
        unique=True,
    )
    op.create_table(
        "django_content_type",
        sa.Column("id", mysql.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("app_label", mysql.VARCHAR(length=100), nullable=False),
        sa.Column("model", mysql.VARCHAR(length=100), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        mysql_default_charset="latin1",
        mysql_engine="InnoDB",
    )
    op.create_index(
        op.f("django_content_type_app_label_model_76bd3d3b_uniq"),
        "django_content_type",
        ["app_label", "model"],
        unique=True,
    )
    op.create_table(
        "auth_user",
        sa.Column("id", mysql.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("password", mysql.VARCHAR(length=128), nullable=False),
        sa.Column("last_login", mysql.DATETIME(fsp=6), nullable=True),
        sa.Column(
            "is_superuser",
            mysql.TINYINT(display_width=1),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column("username", mysql.VARCHAR(length=150), nullable=False),
        sa.Column("first_name", mysql.VARCHAR(length=150), nullable=False),
        sa.Column("last_name", mysql.VARCHAR(length=150), nullable=False),
        sa.Column("email", mysql.VARCHAR(length=254), nullable=False),
        sa.Column(
            "is_staff",
            mysql.TINYINT(display_width=1),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "is_active",
            mysql.TINYINT(display_width=1),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column("date_joined", mysql.DATETIME(fsp=6), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        mysql_default_charset="latin1",
        mysql_engine="InnoDB",
    )
    op.create_index(op.f("username"), "auth_user", ["username"], unique=True)
    op.create_table(
        "django_admin_log",
        sa.Column("id", mysql.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("action_time", mysql.DATETIME(fsp=6), nullable=False),
        sa.Column("object_id", mysql.LONGTEXT(), nullable=True),
        sa.Column("object_repr", mysql.VARCHAR(length=200), nullable=False),
        sa.Column(
            "action_flag",
            mysql.SMALLINT(unsigned=True),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column("change_message", mysql.LONGTEXT(), nullable=False),
        sa.Column(
            "content_type_id", mysql.INTEGER(), autoincrement=False, nullable=True
        ),
        sa.Column("user_id", mysql.INTEGER(), autoincrement=False, nullable=False),
        sa.ForeignKeyConstraint(
            ["content_type_id"],
            ["django_content_type.id"],
            name=op.f("django_admin_log_content_type_id_c4bce8eb_fk_django_co"),
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["auth_user.id"],
            name=op.f("django_admin_log_user_id_c564eba6_fk_auth_user_id"),
        ),
        sa.PrimaryKeyConstraint("id"),
        mysql_default_charset="latin1",
        mysql_engine="InnoDB",
    )
    op.create_table(
        "django_session",
        sa.Column("session_key", mysql.VARCHAR(length=40), nullable=False),
        sa.Column("session_data", mysql.LONGTEXT(), nullable=False),
        sa.Column("expire_date", mysql.DATETIME(fsp=6), nullable=False),
        sa.PrimaryKeyConstraint("session_key"),
        mysql_default_charset="latin1",
        mysql_engine="InnoDB",
    )
    op.create_index(
        op.f("django_session_expire_date_a5c62663"),
        "django_session",
        ["expire_date"],
        unique=False,
    )
    op.create_table(
        "auth_group",
        sa.Column("id", mysql.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("name", mysql.VARCHAR(length=150), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        mysql_default_charset="latin1",
        mysql_engine="InnoDB",
    )
    op.create_index(op.f("name"), "auth_group", ["name"], unique=True)
    # ### end Alembic commands ###
